// import {Routes} from '@angular/router'
// import { DashboardComponent }   from './dashboard/dashboard.component';
// import { HeroesComponent }      from './heroes/heroes.component';
// import { HeroDetailComponent }  from './hero-detail/hero-detail.component';
// import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';

// export const ROUTES: Routes= [
//     { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
//     { path: 'dashboard', component: DashboardComponent },
//     { path: 'detail/:id', component: HeroDetailComponent },
//     { path: 'heroes', component: HeroesComponent },
//     {
//         path: 'auto-generated',
//         component: AutoGeneratedComponent,
//     },
//   ];
  